const allData = [
  {
    image: 'car.png',
    alt: 'Cars back and front end app',
    github: 'https://github.com/zkr024/Cars',
    link: 'https://cars-capstone.herokuapp.com/',
    description: 'This is a back and front-end project. A database that stores data to handle the car front-end app CRUD operations. The API was set to be accessed only when the user has been authenticated and each of the requests is made with JWT. The front displays a list of items that can be selected to schedule to be tested. Also is possible to remove the selected items and see a list of the booked appointments.',
    technologies: ['Ruby on Rails', 'PostgreSql', 'React JS', 'Redux', 'HTML', 'CSS', 'Bootstrap'],
  },
  {
    image: 'financial.png',
    alt: 'Financial app',
    github: 'https://github.com/zkr024/financial-metrics',
    link: 'https://peppy-tarsier-ec49cb.netlify.app/',
    description: 'The application displays the last years financial records from the most important companies in the word. It is built using react and redux and it feeds from the Financial Modeling Prep API.',
    technologies: ['Javascript', 'React JS', 'Redux'],
  },
  {
    image: 'apiApp.png',
    alt: 'tv series web app',
    github: 'https://github.com/zkr024/API-Based-App',
    link: 'https://zkr024.github.io/API-Based-App/',
    description: 'This app was built using an external API. Contains information from some tv series and allows the user to leave comments on a selected item.',
    technologies: ['JavaScript', 'HTML', 'CSS', 'Webpack'],
  },
  {
    image: 'capstone.png',
    alt: 'rock concert app',
    github: 'https://github.com/zkr024/Capstone-Project',
    link: 'https://zkr024.github.io/Capstone-Project/',
    description: 'Responsive site from mobile to desktop. It was based on Cindy Shin in Behance design. It changes in between the from screen and the about page.The concept was to simulate a promotion to a big rock concert.',
    technologies: ['JavaScript', 'HTML', 'CSS'],
  },
  {
    image: 'basePort.png',
    alt: 'basic portfolio design',
    github: 'https://github.com/zkr024/Portfolio',
    link: 'https://zkr024.github.io/Portfolio/',
    description: 'This is a mobile/desktop responsive app. The design was taken from Figma. Used CSS Flexbox and Grid to enable the responsiveness. Also used JavaScript to enable/disable the mobile menu from the navbar.',
    technologies: ['JavaScript', 'HTML', 'CSS'],
  },
  {
    image: 'space.png',
    alt: 'Web app to booked space travels',
    github: 'https://github.com/zkr024/space-travelers',
    link: 'https://fancy-cannoli-7d094e.netlify.app/',
    description: 'A web App that takes and displays information from an API. It allows the user to reserve and removes reservations from two different categories. Within the profile tab, the user can see the list of the selected reservations.',
    technologies: ['React JS', 'Javascript', 'CSS'],

  },
  {
    image: 'math.png',
    alt: 'Calculator app',
    github: 'https://github.com/zkr024/Math-Magicians',
    link: 'https://math-zkr.herokuapp.com/',
    description: 'A simple app that contains different tabs. the calculator is able to manage the logic of simple math operations and displays an error when wrong data is entered. it was built using React',
    technologies: ['JavaScript', 'HTML', 'CSS'],
  },
  {
    image: 'budget.png',
    alt: 'Mobile budget app',
    github: 'https://github.com/zkr024/Budget-app',
    link: 'https://morning-oasis-24983.herokuapp.com/',
    description: 'A mobile app built with rails and PostgreSQL. After signing in the user is able to add categories and see how much has been spent in each added category. Can add transactions after selecting the category that they fell under and assign more categories if needed.',
    technologies: ['Ruby', 'Ruby on rails', 'PostgreSql', 'CSS'],
  },
  {
    image: 'leaderBoard.png',
    alt: 'leader board web app',
    github: 'https://github.com/zkr024/Leaderboard',
    link: 'https://zkr024.github.io/Leaderboard/',
    description: 'App to add name and score to the leader-board. Use Js to add functionality: -Add records. -Use localStorage to keep records. -Modules to separate functions. Use webpack to compile all the files.',
    technologies: ['JavaScript', 'HTML', 'CSS', 'Webpack'],
  }];

export default allData;
